### ISSUE TITLE
What is the hardest thing about teaching yourself how to code?

### ISSUE THREAD

**Issue by CarlMungazi** [sethmcleod/ama#1]

**Comment by sethmcleod** [comment]
Good question!

I'd like to consider myself a fast learner; it usually doesn't take me long to grasp new concepts. So I wouldn't consider the process of learning difficult, but rather _figuring out what to learn_. With new frameworks, tools and libraries popping up every day, it's tough to look past the trends and find the long term value of a particular language or tool. 

Aside from that, I sometimes have _trouble retaining information_. With so many great learning tools out there, like [CodeSchool](https://www.codeschool.com/) and [EggHead](https://egghead.io/), it's really easy to fall into a habit of just consuming and never doing anything with the stuff you learn. In my opinion, hands on experience will teach you faster than any course or lecture. 

My advice to anyone teaching themselves how to code is to keep doing side projects. Even if it's something simple, or something that's already been done, the deliberate practice is what's really going to make that concept stick.
