### ISSUE TITLE
What's your current job?

### ISSUE THREAD

**Issue by itzsaga** [sethmcleod/ama#2]

**Comment by sethmcleod** [comment]
For the past year and a half I've been working with a fantastic team at the [Menuat](https://menuat.com), a digital menu startup for restaurants and bars. At the end of this week I'll be leaving that job and doing freelance projects full-time. 

I'm a member of [CodeMentor](https://codementor.com), where I help individuals and teams with their code issues. Also I was recently accepted into the engineering team at [Gigster](https://gigster.com), a stellar company that allows developers to work remotely on projects based around the world.
